config/routes.rb
Rails.application.routes.draw do
  devise_for :users

      devise_scope  :user do
    get 'users/sign_out' => 'devise/sessions#destroy'
      end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  root "recipes#index"
    resources :foods, only: [:index, :new, :create, :destroy]
    resources :recipes, only: [:index, :show, :new, :create, :destroy] do
      resources :recipe_foods, only: [:create, :new, :destroy, :update, :edit] 
    end

  
  post 'toggle_visible', to: 'recipes#toggle_visible', as: 'toggle_visible'

  get '/public_recipes' => 'recipes#public_recipes'
  get '/shopping_list' => 'recipes#shopping_list'
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    return unless user.present?

    can :manage, Recipe, user:

    # Define abilities for the user here. For example:
    #
    #   return unless user.present?
    #   can :read, :all
    #   return unless user.admin?
    #   can :manage, :all
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, published: true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/blob/develop/docs/define_check_abilities.md
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/food.rb
class Food < ApplicationRecord
  belongs_to :user
  has_many :recipe_foods, dependent: :destroy
  has_many :recipes, through: :recipe_foods

  validates :name, presence: true
  validates :price, presence: true
  validates :user_id, presence: true
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  belongs_to :user
  has_many :recipe_foods, dependent: :destroy
  has_many :foods, through: :recipe_foods

  validates :name, presence: true
  validates :preparation_time, presence: true
  validates :cooking_time, presence: true
  validates :description, presence: true
end

app/models/recipe_food.rb
class RecipeFood < ApplicationRecord
  belongs_to :recipe
  belongs_to :food

  validates :quantity, presence: true, numericality: { greater_than: 0 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable

  has_many :foods
  has_many :recipes

  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    # Permit the `subscribe_newsletter` parameter along with the other
    # sign up parameters.
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController
  def index
    @foods = Food.where(user_id: current_user.id)
  end

  def new
    @food = Food.new
  end

  def create
    values = params.require(:food).permit(:name, :measurement_unit, :price, :quantity)
    @food = Food.new(name: values[:name], measurement_unit: values[:measurement_unit], price: values[:price],
                     quantity: values[:quantity], user_id: current_user.id)

    if @food.save
      redirect_to root_path,
                  notice: 'your food item was added to the database'
    else
      render :new
    end
  end

  def destroy
    @food = Food.find(params[:id])
    @food.destroy
    @recipe_food = RecipeFood.find(params[:id])
    @recipe_food.destroy
    redirect_to request.referrer
  end
end

app/controllers/recipe_foods_controller.rb
class RecipeFoodsController < ApplicationController
  def new
    @recipe_food = RecipeFood.new
  end

  def create
    @recipe_food = RecipeFood.new(recipe_food_params)
    if @recipe_food.save
      redirect_to recipe_path(@recipe_food.recipe)
    else
      render :new
    end
  end

  def edit
    @recipe_food = RecipeFood.find(params[:id])
  end

  def update
    @recipe_food = RecipeFood.find(params[:id])
    if @recipe_food.update(recipe_food_params)
      redirect_to recipe_path(@recipe_food.recipe)
    else
      render :edit
    end
  end

  def destroy
    @recipe_food = RecipeFood.find(params[:id])
    @recipe_food.destroy
    redirect_to request.referrer
  end

  private

  def recipe_food_params
    params.require(:recipe_food).permit(:food_id, :quantity).merge(recipe_id: params[:recipe_id])
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  def index
    @recipes = Recipe.where(user_id: current_user.id)
  end

  def show
    @recipe = Recipe.find(params[:id])
  end

  def new
    @recipe = Recipe.new
  end

  def create
    values = params.require(:recipe).permit(:name, :preparation_time, :cooking_time, :description)
    @recipe = Recipe.new(name: values[:name], preparation_time: values[:preparation_time],
                         cooking_time: values[:cooking_time], description: values[:description],
                         user_id: current_user.id)

    if @recipe.save
      redirect_to recipes_path,
                  notice: 'your recipe was added to the database'
    else
      render :new
    end
  end

  def destroy
    @recipe = Recipe.find(params[:id])

    @recipe.destroy
    redirect_to recipes_path
  end

  def toggle_visible
    @recipe = Recipe.find(params[:id])
    @recipe.toggle!(:public)

    if @recipe.save
      redirect_to recipe_path(@recipe.id),
                  notice: 'Your recipe Visibility has changed'
    else
      render :new
    end
  end

  def public_recipes
    @recipes = Recipe.where(public: true).order(created_at: :desc).includes(:user, :recipe_foods)
  end

  def shopping_list
    @requirements = []
    # Take all the foods from the current user's recipes and add them to the requirements array
    current_user.foods.each do |food|
      food_quantity = food.quantity
      food_required = food.recipe_foods.sum(:quantity)
      diff = food_required - food_quantity
      # if the required quantity is greater than 0, add it to the requirements array
      @requirements << { name: food.name, diff:, price: food.price * diff } if diff.positive?
    end
    # Calculate the total cost of the shopping list
    @total_cost = @requirements.sum { |h| h[:price] }
    # Calculate the total number of elements in the shopping list
    @total_elements = @requirements.size
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def new
    @user = User.new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/recipe_foods_helper.rb
module RecipeFoodsHelper
end

app/views/foods/index.html.erb
<%= render 'shared/navigation', post: @post%>

<div class="sm:flex justify-center p-5">
<h1 class="text-2xl font-normal leading-normal mt-0 mb-2">  
List of foods </h1>
</div>

  
  <div class="sm:flex flex-col items-center mb-5">
<%=link_to "Add Food to List", new_food_path, class: "bg-red-500 hover:bg-red-400 text-white font-bold py-2 px-4 border-b-4 border-red-700 hover:border-red-500 rounded" %>
</div>


<div class="sm:flex sm:justify-center">
<table class="w-9/12">
  <tr class="w-1/2 bg-red-500 text-white">
      <th>Food</th>
      <th>Quatity</th>
      <th>Price</th>
      <th>Actions</th>
  </tr>
<tbody>
<% @foods.each do |food| %>
      <tr class="even:bg-gray-300">
        <td><%= food.name %></td>
        <td><%= food.quantity%> <%= food.measurement_unit %>  </td>
           <td>$<%= food.price %></td>
        <td><%= button_to 'Delete', food_path(food.id), method: :delete, data: { confirm: 'Are you sure?' }, class: "hover:underline hover:font-bold hover:text-red-500"  %> </td>
      </tr>
      <% end %>
</tbody>
</table>

</div>

app/views/foods/new.html.erb
<%= render 'shared/navigation', post: @post%>

<div class="sm:flex justify-center p-5">
 <h1 class="text-2xl font-normal leading-normal mt-0 mb-2">  
New Item </h1>
</div>

 <div class="sm:flex justify-center p-5 border-2 border-gray-300">
  <%= form_with model: @food do |form|%>
    <div>
      <%= form.label :name%> <br>
      <%= form.text_field :name%>
    </div>

    <div>
      <%= form.label :quantity%> <br>
      <%= form.text_field :quantity%>
    </div>

    <div>
      <%= form.label :measurement_unit%> <br>
      <%= form.select :measurement_unit, ['grams', 'mililiters', 'units', 'slices']%>
    </div>

    <div>
      <%= form.label :price%> <br>
      <%= form.number_field :price, step: :any%>
    </div>

    <%= form.submit "Create Food", class: "bg-red-500 hover:bg-red-400 text-white font-bold py-2 px-4 border-b-4 border-red-700 hover:border-red-500 rounded"%>
  
  <%end%>
</div> 

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RecipesRails</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

  <script src="https://cdn.tailwindcss.com"></script>    
  <%= javascript_importmap_tags %>
  </head>

  <body>

       <p class="notice"><%= notice %></p>
       <p class="alert"><%= alert %></p>

    <%= yield %>
  </body>
</html>

app/views/recipe_foods/edit.html.erb
<%= render 'shared/navigation', post: @post%>

<%= form_with model: @recipe_food, url: recipe_recipe_food_path, method: :patch do |f| %>
  <%= f.label :food %>
  <%= f.select :food_id, Food.all.map { |food| [food.name, food.id] } %>
  <%= f.label :quantity %>
  <%= f.text_field :quantity %>
  <%= f.submit "Edit" %>
<%end%>

app/views/recipe_foods/new.html.erb
<%= render 'shared/navigation', post: @post%>

<%= form_with model: @recipe_food, url: recipe_recipe_foods_path, method: :post do |f| %>

  <%= f.label :food %>
  <%= f.select :food_id, current_user.foods.all.map { |food| [food.name, food.id] } %>
  <%= f.label :quantity %>
  <%= f.text_field :quantity %>
  <%= f.submit "Add" %>
<%end%>

app/views/recipes/index.html.erb
<%= render 'shared/navigation', post: @post%>

<div class="sm:flex justify-center p-5">
<h1 class="text-2xl font-normal leading-normal mt-0 mb-2"> 
Your Recipes </h1>
</div>

  

<div class="sm:flex flex-col items-center">
<%=link_to "Add New Recipe", new_recipe_path, class: "bg-red-500 hover:bg-red-400 text-white font-bold py-2 px-4 border-b-4 border-red-700 hover:border-red-500 rounded" %> 
  <% @recipes.includes([:user]).each do |recipe| %>


    <div class="border-2 border-gray-300 hover:border-gray-500 w-auto m-2 p-2 bg-white sm:flex items-center justify-between w-6/12">
        <div class="sm:flex flex-col ">
          <%= link_to recipe_path(recipe.id) do %>
            <%= recipe.name %>
          <%end%> 
          <% if can? :destroy, recipe %>
            <%= button_to 'Remove', recipe_path(recipe.id), method: :delete, class: "hover:underline hover:font-bold hover:text-red-500" %>
          <% end %>
        </div> 
        <%= link_to recipe_path(recipe.id) do %>
          <%= recipe.description %>
         <%end%> 
    </div>
  
    
  
  <% end %>
</div>

app/views/recipes/new.html.erb
<%= render 'shared/navigation', post: @post%>

<div class="sm:flex justify-center p-5">
<h1 class="text-2xl font-normal leading-normal mt-0 mb-2">  
New Recipe </h1>
</div>
 
 <div class="sm:flex justify-center p-5 border-2 border-gray-300">
  <%= form_with model: @recipe do |form|%>
    <div>
      <%= form.label :name%> <br>
      <%= form.text_field :name%>
    </div>

    <div>
      <%= form.label :preparation_time%> <br>
      <%= form.text_field :preparation_time%>
    </div>

    <div>
      <%= form.label :cooking_time%> <br>
      <%= form.text_field :cooking_time%>
    </div>

    <div>
      <%= form.label :description%> <br>
      <%= form.text_area :description%>
    </div>

    <%= form.submit "Create Recipe", class: "bg-red-500 hover:bg-red-400 text-white font-bold py-2 px-4 border-b-4 border-red-700 hover:border-red-500 rounded"%>
  
  <%end%>
</div> 

app/views/recipes/public_recipes.html.erb
<%= render 'shared/navigation', post: @post%>

<div class="sm:flex justify-center p-5">
<h1 class="text-2xl font-normal leading-normal mt-0 mb-2"> 
All Recipes </h1>
</div>

<div class="sm:flex flex-col items-center">

  <% @recipes.each do |recipe| %>
  

      <%= link_to recipe_path(recipe.id), class: "border-2 border-gray-300 hover:border-gray-500 m-2 p-2 bg-white sm:flex items-center justify-between w-6/12" do %>

        <div class="sm:flex flex-col">
          <p><%= recipe.name %> </p>
          <p>by: <%= recipe.user.name%> </p>
        </div>
        <div class="sm:flex flex-col">
          <p>total items: <%= recipe.recipe_foods.length%> </p>
          <%cost = []%>
          <% recipe.recipe_foods.includes([:food]).each do |food| %>
            <% cost << food.quantity * food.food.price%>
         <%end%>
          <p>$<%=cost.sum%></p>
        </div>
        
      <%end%>
    
  <% end %> 

</div>

app/views/recipes/shopping_list.html.erb
<%= render 'shared/navigation', post: @post%>

<div class="sm:flex justify-center p-5">
<h1 class="text-2xl font-normal leading-normal mt-0 mb-2"> 
Shopping List </h1>
</div>

<div class="sm:flex flex-col items-center">
<div class="border-2 border-gray-300 w-auto m-2 p-2 bg-white sm:flex items-center justify-between w-6/12">
<h2>Total elements: <%=@total_elements%> </h2>
<h2>Total cost: $<%=@total_cost%> </h2>
</div>

<table class="w-4/12">
  <tr class="w-1/2 bg-red-500 text-white">
      <th>Food</th>
      <th>Quantity</th>
      <th>Price</th> 
  </tr>
<tbody>
  <% @requirements.each do |item| %>
  <tr class="even:bg-gray-300">
  <td> <%= item[:name]%> </td>
  <td> <%= item[:diff] %> </td>
  <td> $<%= item[:price] %> </td>
  <% end %>
  </tr>
</tbody>
</table>
</div>

app/views/recipes/show.html.erb
<%= render 'shared/navigation', post: @post%>

<div class="sm:flex justify-center p-5">
<h1 class="text-2xl font-normal leading-normal mt-0 mb-2">  
<%= @recipe.name %> </h1>
</div>

<div class="sm:flex sm:justify-center space-x-48">
<div>
<p>Preparation time: <%= @recipe.preparation_time%></p>
<p>Cooking time: <%= @recipe.cooking_time%> <br></p>
</div>
<div>
       <% if can? :manage, @recipe %>
            <% if @recipe.public? == true %>
       <%= button_to 'Private ═⚪ Public', toggle_visible_path(id: @recipe.id), method: :post, class: "bg-red-500 hover:bg-red-400 text-white font-bold py-2 px-4 border-b-4 border-red-700 hover:border-red-500 rounded" %>
            <% else %>
      <%= button_to 'Private ⚪═ Public', toggle_visible_path(id: @recipe.id), method: :post, class: "bg-red-500 hover:bg-red-400 text-white font-bold py-2 px-4 border-b-4 border-red-700 hover:border-red-500 rounded" %>
      <% end %>
<%end%>      
</div>
</div>

<div class="sm:flex sm:justify-center m-5 text-center">
How to prepare <%= @recipe.name %>: <br>
<%= @recipe.description%> 
</div>



<div class="sm:flex sm:justify-center m-5">
      <%= link_to 'Generate Shopping List', shopping_list_path, method: :post, class: "m-2 bg-red-500 hover:bg-red-400 text-white font-bold py-2 px-4 border-b-4 border-red-700 hover:border-red-500 rounded" %>
      <% if can? :manage, @recipe %>
        <%= link_to 'Add ingredient', new_recipe_recipe_food_path(@recipe), class: "m-2 bg-red-500 hover:bg-red-400 text-white font-bold py-2 px-4 border-b-4 border-red-700 hover:border-red-500 rounded" %>
      <% end %>  
</div>

<div class="sm:flex sm:justify-center table-auto">
<table class="w-5/12">
  <tr class="w-1/2 bg-red-500 text-white">
      <th>Food</th>
      <th>Quatity</th>
      <th>Price</th>
      <th>Actions</th>
  </tr>
<tbody>
      <% @recipe.recipe_foods.includes([:food]).each do |recipe_food| %>
      <tr class="even:bg-gray-300">
        <td><%= recipe_food.food.name %></td>
        <td><%= recipe_food.quantity %></td>
        <td><%= recipe_food.food.price * recipe_food.quantity%></td>
        <td>
              <% if can? :manage, @recipe %>
              <div class="sm:flex sm:justify-center">
              <%= link_to 'Edit', edit_recipe_recipe_food_path(@recipe, recipe_food), class: "hover:underline hover:font-bold px-2" %>
              <%= button_to 'Delete', recipe_recipe_food_path(@recipe, recipe_food), method: :delete, data: { confirm: 'Are you sure?' }, class: "hover:underline hover:font-bold hover:text-red-500 px-2" %>
              <div>
                  <% end %>
      </tr>
      <% end %>
</tbody>
</table>
</div>

app/views/shared/_navigation.html.erb
  <div class="mx-auto bg-red-700 shadow-lg sm:content-around sm:py-4 sm:flex sm:justify-center sm:space-x-20 text-white font-bold">
    <%=link_to "Your Recipes🍔", root_path, class: "hover:underline" %>
    <%= link_to "All Public Recipes📖", public_recipes_path, class: "hover:underline" %>
    <%= link_to "Food Items📝", foods_path, class: "hover:underline" %>  
    <%= link_to "Shopping List🛒", shopping_list_path, class: "hover:underline" %>
    <%= link_to "Logout👋", destroy_user_session_path, class: "hover:underline" %>  
  </div>